name: Keep Server Alive

on:
  schedule:
    - cron: "*/14 * * * *" # Every 14 minutes (UTC time)

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Ping
        run: curl https://collaborative-whiteboard-backend-dd0a.onrender.com
